/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { School, Teacher, Student, Report, AttendanceTeacher, AttendanceStudent, Inventory, District, Village, Log, SystemSettings } from './types';

export const districts: District[] = [
  { id: 'dist-1', name: 'Klaten Utara' }
];

export const villages: Village[] = [
  { id: 'vil-1', district_id: 'dist-1', name: 'Bareng Lor' },
  { id: 'vil-2', district_id: 'dist-1', name: 'Karanganom' },
  { id: 'vil-3', district_id: 'dist-1', name: 'Gergunung' },
  { id: 'vil-4', district_id: 'dist-1', name: 'Jati' },
  { id: 'vil-5', district_id: 'dist-1', name: 'Belang Wetan' },
  { id: 'vil-6', district_id: 'dist-1', name: 'Jonggrangan' },
  { id: 'vil-7', district_id: 'dist-1', name: 'Ketandan' },
  { id: 'vil-8', district_id: 'dist-1', name: 'Mayungan' }
];

export const schools: School[] = [
  {
    id: 'school-1',
    name: 'TK Aisyiyah Bustanul Athfal Gergunung',
    npsn: '20363248',
    nsm: '111233050012',
    status: 'Swasta',
    jenjang: 'TK',
    alamat: 'Jl. Ki Hajar Dewantara No. 15, Gergunung',
    kelurahan: 'Gergunung',
    kecamatan: 'Klaten Utara',
    kabupaten: 'Klaten',
    provinsi: 'Jawa Tengah',
    kode_pos: '57438',
    telepon: '0272-321456',
    email: 'aba.gergunung@gmail.com',
    website: 'https://abageringunung.sch.id',
    kepala_sekolah: 'Wahyuningsih, S.Pd',
    nip_kepala: '-',
    akreditasi: 'A',
    status_tanah: 'Milik Sendiri',
    status_gedung: 'Milik Sendiri',
    luas_tanah: 400,
    luas_bangunan: 250,
    jumlah_ruang: 5,
    jumlah_toilet: 2,
    tahun_berdiri: '1980',
    tahun_operasional: '1982',
    latitude: '-7.6912',
    longitude: '110.6124',
    foto_url: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=1200&auto=format&fit=crop&q=80',
    logo_url: '',
    status_aktif: 'Aktif',
    username_petugas: 'tkabagergunung',
    password_petugas: 'tkabagergunung'
  },
  {
    id: 'school-2',
    name: 'TK Aisyiyah Bustanul Athfal Bareng Lor',
    npsn: '20338779',
    nsm: '111233050013',
    status: 'Swasta',
    jenjang: 'TK',
    alamat: 'Jl. Pemuda Utara No. 42, Bareng Lor',
    kelurahan: 'Bareng Lor',
    kecamatan: 'Klaten Utara',
    kabupaten: 'Klaten',
    provinsi: 'Jawa Tengah',
    kode_pos: '57438',
    telepon: '0272-321789',
    email: 'aba.barenglor@gmail.com',
    website: 'https://ababarenglor.sch.id',
    kepala_sekolah: 'Sri Setyowati, S.Pd',
    nip_kepala: '-',
    akreditasi: 'A',
    status_tanah: 'Wakaf',
    status_gedung: 'Milik Sendiri',
    luas_tanah: 350,
    luas_bangunan: 200,
    jumlah_ruang: 4,
    jumlah_toilet: 2,
    tahun_berdiri: '1975',
    tahun_operasional: '1977',
    latitude: '-7.6950',
    longitude: '110.6080',
    foto_url: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=1200&auto=format&fit=crop&q=80',
    logo_url: '',
    status_aktif: 'Aktif',
    username_petugas: 'tkababarenglor',
    password_petugas: 'tkababarenglor'
  },
  {
    id: 'school-3',
    name: 'TK Aisyiyah Bustanul Athfal Bramen',
    npsn: '20338781',
    nsm: '111233050014',
    status: 'Swasta',
    jenjang: 'TK',
    alamat: 'Bramen, Klaten Utara',
    kelurahan: 'Bramen',
    kecamatan: 'Klaten Utara',
    kabupaten: 'Klaten',
    provinsi: 'Jawa Tengah',
    kode_pos: '57435',
    telepon: '-',
    email: 'aba.bramen@gmail.com',
    website: '',
    kepala_sekolah: 'Mulyani, S.Pd',
    nip_kepala: '-',
    akreditasi: 'B',
    status_tanah: 'Wakaf',
    status_gedung: 'Milik Sendiri',
    luas_tanah: 300,
    luas_bangunan: 180,
    jumlah_ruang: 3,
    jumlah_toilet: 1,
    tahun_berdiri: '1985',
    tahun_operasional: '1987',
    latitude: '-7.6850',
    longitude: '110.6150',
    foto_url: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200&auto=format&fit=crop&q=80',
    logo_url: '',
    status_aktif: 'Aktif',
    username_petugas: 'tkababramen',
    password_petugas: 'tkababramen'
  },
  {
    id: 'school-4',
    name: 'TK Aisyiyah ABA III Gunungan',
    npsn: '20338782',
    nsm: '111233050015',
    status: 'Swasta',
    jenjang: 'TK',
    alamat: 'Gunungan, Klaten Utara',
    kelurahan: 'Gergunung',
    kecamatan: 'Klaten Utara',
    kabupaten: 'Klaten',
    provinsi: 'Jawa Tengah',
    kode_pos: '57438',
    telepon: '0272-321122',
    email: 'aba.gunungan3@gmail.com',
    website: '',
    kepala_sekolah: 'Sri Mulyani, S.Pd',
    nip_kepala: '-',
    akreditasi: 'A',
    status_tanah: 'Wakaf',
    status_gedung: 'Milik Sendiri',
    luas_tanah: 320,
    luas_bangunan: 190,
    jumlah_ruang: 4,
    jumlah_toilet: 2,
    tahun_berdiri: '1988',
    tahun_operasional: '1990',
    latitude: '-7.6900',
    longitude: '110.6100',
    foto_url: 'https://images.unsplash.com/photo-1564981797816-1043d01117da?w=1200&auto=format&fit=crop&q=80',
    logo_url: '',
    status_aktif: 'Aktif',
    username_petugas: 'tkabagunungan',
    password_petugas: 'tkabagunungan'
  },
  {
    id: 'school-5',
    name: 'TK Aisyiyah Bustanul Athfal Ketandan I',
    npsn: '20338785',
    nsm: '111233050016',
    status: 'Swasta',
    jenjang: 'TK',
    alamat: 'Ketandan, Klaten Utara',
    kelurahan: 'Ketandan',
    kecamatan: 'Klaten Utara',
    kabupaten: 'Klaten',
    provinsi: 'Jawa Tengah',
    kode_pos: '57438',
    telepon: '0272-321445',
    email: 'aba.ketandan1@gmail.com',
    website: '',
    kepala_sekolah: 'Siti Rahmawati, S.Pd',
    nip_kepala: '-',
    akreditasi: 'A',
    status_tanah: 'Milik Sendiri',
    status_gedung: 'Milik Sendiri',
    luas_tanah: 380,
    luas_bangunan: 220,
    jumlah_ruang: 4,
    jumlah_toilet: 2,
    tahun_berdiri: '1991',
    tahun_operasional: '1993',
    latitude: '-7.6930',
    longitude: '110.6180',
    foto_url: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=1200&auto=format&fit=crop&q=80',
    logo_url: '',
    status_aktif: 'Aktif'
  },
  {
    id: 'school-6',
    name: 'TK Aisyiyah Bustanul Athfal Ketandan II',
    npsn: '20338786',
    nsm: '111233050017',
    status: 'Swasta',
    jenjang: 'TK',
    alamat: 'Jl. Ketandan Baru No. 8, Ketandan',
    kelurahan: 'Ketandan',
    kecamatan: 'Klaten Utara',
    kabupaten: 'Klaten',
    provinsi: 'Jawa Tengah',
    kode_pos: '57438',
    telepon: '-',
    email: 'aba.ketandan2@gmail.com',
    website: '',
    kepala_sekolah: 'Dwi Astuti, S.Pd',
    nip_kepala: '-',
    akreditasi: 'A',
    status_tanah: 'Wakaf',
    status_gedung: 'Milik Sendiri',
    luas_tanah: 310,
    luas_bangunan: 170,
    jumlah_ruang: 3,
    jumlah_toilet: 1,
    tahun_berdiri: '1995',
    tahun_operasional: '1996',
    latitude: '-7.6945',
    longitude: '110.6195',
    foto_url: 'https://images.unsplash.com/photo-1471286174243-e7a4d9ab6340?w=1200&auto=format&fit=crop&q=80',
    logo_url: '',
    status_aktif: 'Aktif'
  },
  {
    id: 'school-7',
    name: 'TK Aisyiyah Bustanul Athfal Sekarsuli',
    npsn: '20338787',
    nsm: '111233050018',
    status: 'Swasta',
    jenjang: 'TK',
    alamat: 'Sekarsuli, Klaten Utara',
    kelurahan: 'Gergunung',
    kecamatan: 'Klaten Utara',
    kabupaten: 'Klaten',
    provinsi: 'Jawa Tengah',
    kode_pos: '57438',
    telepon: '-',
    email: 'aba.sekarsuli@gmail.com',
    website: '',
    kepala_sekolah: 'Tri Lestari, S.Pd',
    nip_kepala: '-',
    akreditasi: 'B',
    status_tanah: 'Milik Sendiri',
    status_gedung: 'Milik Sendiri',
    luas_tanah: 280,
    luas_bangunan: 160,
    jumlah_ruang: 3,
    jumlah_toilet: 1,
    tahun_berdiri: '1998',
    tahun_operasional: '1999',
    latitude: '-7.6980',
    longitude: '110.6220',
    foto_url: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?w=1200&auto=format&fit=crop&q=80',
    logo_url: '',
    status_aktif: 'Aktif'
  },
  {
    id: 'school-8',
    name: 'TK Aisyiyah Bustanul Athfal Karanganom',
    npsn: '20338788',
    nsm: '111233050019',
    status: 'Swasta',
    jenjang: 'TK',
    alamat: 'Karanganom, Klaten Utara',
    kelurahan: 'Karanganom',
    kecamatan: 'Klaten Utara',
    kabupaten: 'Klaten',
    provinsi: 'Jawa Tengah',
    kode_pos: '57438',
    telepon: '0272-321155',
    email: 'aba.karanganom@gmail.com',
    website: '',
    kepala_sekolah: 'Suprihatin, S.Pd',
    nip_kepala: '-',
    akreditasi: 'A',
    status_tanah: 'Wakaf',
    status_gedung: 'Milik Sendiri',
    luas_tanah: 420,
    luas_bangunan: 260,
    jumlah_ruang: 5,
    jumlah_toilet: 2,
    tahun_berdiri: '1972',
    tahun_operasional: '1974',
    latitude: '-7.6905',
    longitude: '110.6050',
    foto_url: 'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?w=1200&auto=format&fit=crop&q=80',
    logo_url: '',
    status_aktif: 'Aktif'
  }
];

export const teachers: Teacher[] = [
  // School 1 (TK ABA Gergunung) Teachers
  {
    id: 'teacher-1',
    school_id: 'school-1',
    nama: 'Wahyuningsih, S.Pd',
    nik: '3310014512800003',
    nip: '-',
    tempat_lahir: 'Klaten',
    tanggal_lahir: '1980-05-12',
    jenis_kelamin: 'P',
    alamat: 'Gergunung, Klaten Utara',
    no_hp: '081234567890',
    email: 'wahyuningsih@gmail.com',
    pendidikan: 'S1',
    jurusan: 'PG-PAUD',
    tmt: '2005-01-02',
    status_guru: 'Swasta - GTY',
    jabatan: 'Kepala Sekolah',
    golongan: '-',
    honor: 3000000,
    gty: true,
    gtt: false,
    pns: false,
    pppk: false,
    foto_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=60'
  },
  {
    id: 'teacher-2',
    school_id: 'school-1',
    nama: 'Khadijah, S.Pd',
    nik: '3310014811850002',
    nip: '-',
    tempat_lahir: 'Klaten',
    tanggal_lahir: '1985-11-18',
    jenis_kelamin: 'P',
    alamat: 'Karanganom, Klaten Utara',
    no_hp: '081398765432',
    email: 'khadijah.aba@gmail.com',
    pendidikan: 'S1',
    jurusan: 'Pendidikan Anak Usia Dini',
    tmt: '2012-07-15',
    status_guru: 'Swasta - GTY',
    jabatan: 'Guru Kelas A',
    golongan: '-',
    honor: 2200000,
    gty: true,
    gtt: false,
    pns: false,
    pppk: false,
    foto_url: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=60'
  },
  {
    id: 'teacher-3',
    school_id: 'school-1',
    nama: 'Aisyah Humaira, S.Pd',
    nik: '3310015409920001',
    nip: '-',
    tempat_lahir: 'Klaten',
    tanggal_lahir: '1992-09-14',
    jenis_kelamin: 'P',
    alamat: 'Gergunung, Klaten Utara',
    no_hp: '085612345678',
    email: 'aisyah.humaira@gmail.com',
    pendidikan: 'S1',
    jurusan: 'PG-PAUD',
    tmt: '2016-01-10',
    status_guru: 'Swasta - GTY',
    jabatan: 'Guru Kelas B',
    golongan: '-',
    honor: 2000000,
    gty: true,
    gtt: false,
    pns: false,
    pppk: false,
    foto_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=60'
  },
  {
    id: 'teacher-4',
    school_id: 'school-1',
    nama: 'Rahmat Hidayat, S.Or',
    nik: '3310011202880004',
    nip: '-',
    tempat_lahir: 'Klaten',
    tanggal_lahir: '1988-02-12',
    jenis_kelamin: 'L',
    alamat: 'Bareng Lor, Klaten Utara',
    no_hp: '089876543210',
    email: 'rahmat.hidayat@gmail.com',
    pendidikan: 'S1',
    jurusan: 'Pendidikan Olahraga',
    tmt: '2018-07-20',
    status_guru: 'Swasta - GTT WB',
    jabatan: 'Guru Olahraga',
    golongan: '-',
    honor: 1500000,
    gty: false,
    gtt: true,
    pns: false,
    pppk: false,
    foto_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=60'
  },

  // School 2 (TK ABA Bareng Lor) Teachers
  {
    id: 'teacher-5',
    school_id: 'school-2',
    nama: 'Sri Setyowati, S.Pd',
    nik: '3310014804780001',
    nip: '-',
    tempat_lahir: 'Klaten',
    tanggal_lahir: '1978-04-08',
    jenis_kelamin: 'P',
    alamat: 'Bareng Lor, Klaten Utara',
    no_hp: '081223344556',
    email: 'sri.setyowati@gmail.com',
    pendidikan: 'S1',
    jurusan: 'PG-PAUD',
    tmt: '2008-07-01',
    status_guru: 'Swasta - GTY',
    jabatan: 'Kepala Sekolah',
    golongan: '-',
    honor: 3200000,
    gty: true,
    gtt: false,
    pns: false,
    pppk: false,
    foto_url: 'https://images.unsplash.com/photo-1554151228-14d9def656e4?w=150&auto=format&fit=crop&q=60'
  },
  {
    id: 'teacher-6',
    school_id: 'school-4',
    nama: 'Sri Mulyani, S.Pd',
    nik: '3310014804820005',
    nip: '-',
    tempat_lahir: 'Klaten',
    tanggal_lahir: '1982-04-15',
    jenis_kelamin: 'P',
    alamat: 'Gunungan, Klaten Utara',
    no_hp: '081223344556',
    email: 'sri.mulyani@gmail.com',
    pendidikan: 'S1',
    jurusan: 'PG-PAUD',
    tmt: '2010-07-01',
    status_guru: 'Swasta - GTY',
    jabatan: 'Kepala Sekolah',
    golongan: '-',
    honor: 3200000,
    gty: true,
    gtt: false,
    pns: false,
    pppk: false,
    foto_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=60',
    tahun_pelajaran: '2025/2026',
    semester: 'Ganjil'
  },
  {
    id: 'teacher-7',
    school_id: 'school-4',
    nama: 'Endang Lestari, S.Pd',
    nik: '3310015512880006',
    nip: '-',
    tempat_lahir: 'Klaten',
    tanggal_lahir: '1988-12-05',
    jenis_kelamin: 'P',
    alamat: 'Jonggrangan, Klaten Utara',
    no_hp: '085611223344',
    email: 'endang.lestari@gmail.com',
    pendidikan: 'S1',
    jurusan: 'PG-PAUD',
    tmt: '2015-01-15',
    status_guru: 'Swasta - GTY',
    jabatan: 'Guru Kelas A',
    golongan: '-',
    honor: 2200000,
    gty: true,
    gtt: false,
    pns: false,
    pppk: false,
    foto_url: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=60',
    tahun_pelajaran: '2025/2026',
    semester: 'Ganjil'
  }
];

export const students: Student[] = [
  // School 1 (TK ABA Gergunung) Students
  {
    id: 'student-1',
    school_id: 'school-1',
    nama: 'Muhammad Al-Fatih',
    nik: '3310010508200001',
    nisn: '3201452140',
    tempat_lahir: 'Klaten',
    tanggal_lahir: '2020-08-05',
    jenis_kelamin: 'L',
    nama_ayah: 'Suryaman',
    nama_ibu: 'Nurlaila',
    alamat: 'Gergunung RT 02/05',
    rt: '02',
    rw: '05',
    kelurahan: 'Gergunung',
    kecamatan: 'Klaten Utara',
    kabupaten: 'Klaten',
    provinsi: 'Jawa Tengah',
    agama: 'Islam',
    anak_ke: 1,
    jumlah_saudara: 2,
    status_aktif: 'Aktif',
    tahun_masuk: '2024',
    tahun_pelajaran: '2025/2026',
    semester: 'Ganjil'
  },
  {
    id: 'student-2',
    school_id: 'school-1',
    nama: 'Fatimah Az-Zahra',
    nik: '3310014812200002',
    nisn: '3201452141',
    tempat_lahir: 'Klaten',
    tanggal_lahir: '2020-12-08',
    jenis_kelamin: 'P',
    nama_ayah: 'Andi Wijaya',
    nama_ibu: 'Siti Rohmah',
    alamat: 'Bareng Lor RT 04/01',
    rt: '04',
    rw: '01',
    kelurahan: 'Bareng Lor',
    kecamatan: 'Klaten Utara',
    kabupaten: 'Klaten',
    provinsi: 'Jawa Tengah',
    agama: 'Islam',
    anak_ke: 2,
    jumlah_saudara: 1,
    status_aktif: 'Aktif',
    tahun_masuk: '2024',
    tahun_pelajaran: '2025/2026',
    semester: 'Ganjil'
  },

  // School 2 (TK ABA Bareng Lor) Students
  {
    id: 'student-3',
    school_id: 'school-2',
    nama: 'Ahmad Dahlan',
    nik: '3310011504200003',
    nisn: '3201452145',
    tempat_lahir: 'Klaten',
    tanggal_lahir: '2020-04-15',
    jenis_kelamin: 'L',
    nama_ayah: 'Hasanudin',
    nama_ibu: 'Siti Kalsum',
    alamat: 'Bareng Lor RT 01/02',
    rt: '01',
    rw: '02',
    kelurahan: 'Bareng Lor',
    kecamatan: 'Klaten Utara',
    kabupaten: 'Klaten',
    provinsi: 'Jawa Tengah',
    agama: 'Islam',
    anak_ke: 1,
    jumlah_saudara: 3,
    status_aktif: 'Aktif',
    tahun_masuk: '2024',
    tahun_pelajaran: '2025/2026',
    semester: 'Ganjil'
  },
  {
    id: 'student-4',
    school_id: 'school-4',
    nama: 'Aditya Nugroho',
    nik: '3310011204200004',
    nisn: '3201452148',
    tempat_lahir: 'Klaten',
    tanggal_lahir: '2020-04-12',
    jenis_kelamin: 'L',
    nama_ayah: 'Bambang Nugroho',
    nama_ibu: 'Siti Rahayu',
    alamat: 'Gunungan RT 02/03',
    rt: '02',
    rw: '03',
    kelurahan: 'Gergunung',
    kecamatan: 'Klaten Utara',
    kabupaten: 'Klaten',
    provinsi: 'Jawa Tengah',
    agama: 'Islam',
    anak_ke: 1,
    jumlah_saudara: 1,
    status_aktif: 'Aktif',
    tahun_masuk: '2024',
    tahun_pelajaran: '2025/2026',
    semester: 'Ganjil'
  },
  {
    id: 'student-5',
    school_id: 'school-4',
    nama: 'Ahmad Farhan',
    nik: '3310011508200005',
    nisn: '3201452149',
    tempat_lahir: 'Klaten',
    tanggal_lahir: '2020-08-15',
    jenis_kelamin: 'L',
    nama_ayah: 'Suryo',
    nama_ibu: 'Kartini',
    alamat: 'Gunungan RT 01/03',
    rt: '01',
    rw: '03',
    kelurahan: 'Gergunung',
    kecamatan: 'Klaten Utara',
    kabupaten: 'Klaten',
    provinsi: 'Jawa Tengah',
    agama: 'Islam',
    anak_ke: 2,
    jumlah_saudara: 2,
    status_aktif: 'Aktif',
    tahun_masuk: '2024',
    tahun_pelajaran: '2025/2026',
    semester: 'Ganjil'
  }
];

export const reports: Report[] = [
  {
    id: 'report-1',
    school_id: 'school-1',
    tahun_pelajaran: '2025/2026',
    semester: 'Ganjil',
    bulan: 'Mei',
    hari_belajar: 22,
    status_gedung: 'Milik Sendiri',
    jumlah_ruangan: 4,
    status: 'Approved',
    notes: 'Laporan bulan Mei telah diperiksa dan disetujui.',
    created_at: '2026-05-31T00:00:00Z',
    updated_at: '2026-06-02T08:30:00Z'
  },
  {
    id: 'report-2',
    school_id: 'school-1',
    tahun_pelajaran: '2025/2026',
    semester: 'Ganjil',
    bulan: 'Juni',
    hari_belajar: 22,
    status_gedung: 'Milik Sendiri',
    jumlah_ruangan: 4,
    status: 'Submitted',
    notes: 'Laporan Juni siap direview.',
    created_at: '2026-06-30T00:00:00Z',
    updated_at: '2026-06-30T16:45:00Z'
  }
];

export const attendanceTeachers: AttendanceTeacher[] = [
  // report-1 (Mei, school-1)
  {
    id: 'att-t-1',
    report_id: 'report-1',
    teacher_id: 'teacher-1',
    nama_guru: 'Wahyuningsih, S.Pd',
    jenis_kelamin: 'P',
    hadir: 22,
    izin: 0,
    sakit: 0,
    alpha: 0
  },
  {
    id: 'att-t-2',
    report_id: 'report-1',
    teacher_id: 'teacher-2',
    nama_guru: 'Khadijah, S.Pd',
    jenis_kelamin: 'P',
    hadir: 21,
    izin: 1,
    sakit: 0,
    alpha: 0
  },
  {
    id: 'att-t-3',
    report_id: 'report-1',
    teacher_id: 'teacher-3',
    nama_guru: 'Aisyah Humaira, S.Pd',
    jenis_kelamin: 'P',
    hadir: 22,
    izin: 0,
    sakit: 0,
    alpha: 0
  },
  {
    id: 'att-t-4',
    report_id: 'report-1',
    teacher_id: 'teacher-4',
    nama_guru: 'Rahmat Hidayat, S.Or',
    jenis_kelamin: 'L',
    hadir: 20,
    izin: 0,
    sakit: 2,
    alpha: 0
  },

  // report-2 (Juni, school-1)
  {
    id: 'att-t-5',
    report_id: 'report-2',
    teacher_id: 'teacher-1',
    nama_guru: 'Wahyuningsih, S.Pd',
    jenis_kelamin: 'P',
    hadir: 20,
    izin: 0,
    sakit: 0,
    alpha: 0
  },
  {
    id: 'att-t-6',
    report_id: 'report-2',
    teacher_id: 'teacher-2',
    nama_guru: 'Khadijah, S.Pd',
    jenis_kelamin: 'P',
    hadir: 19,
    izin: 0,
    sakit: 1,
    alpha: 0
  }
];

export const attendanceStudents: AttendanceStudent[] = [
  // report-1
  {
    id: 'att-s-1',
    report_id: 'report-1',
    jenis_kelamin: 'L',
    hadir: 44,
    izin: 0,
    sakit: 0,
    alpha: 0
  },
  {
    id: 'att-s-2',
    report_id: 'report-1',
    jenis_kelamin: 'P',
    hadir: 42,
    izin: 1,
    sakit: 1,
    alpha: 0
  },

  // report-2
  {
    id: 'att-s-3',
    report_id: 'report-2',
    jenis_kelamin: 'L',
    hadir: 40,
    izin: 0,
    sakit: 0,
    alpha: 0
  },
  {
    id: 'att-s-4',
    report_id: 'report-2',
    jenis_kelamin: 'P',
    hadir: 38,
    izin: 1,
    sakit: 1,
    alpha: 0
  }
];

export const inventories: Inventory[] = [
  // report-1
  { id: 'inv-1', report_id: 'report-1', item_name: 'Alat Bermain Luar (Prosotan/Ayunan)', quantity: 2, status_baik: 2, status_rusak: 0 },
  { id: 'inv-2', report_id: 'report-1', item_name: 'Alat Bermain Dalam (APE)', quantity: 15, status_baik: 14, status_rusak: 1 },
  { id: 'inv-3', report_id: 'report-1', item_name: 'Kursi Anak', quantity: 30, status_baik: 28, status_rusak: 2 },
  { id: 'inv-4', report_id: 'report-1', item_name: 'Meja Anak', quantity: 15, status_baik: 15, status_rusak: 0 },
  { id: 'inv-5', report_id: 'report-1', item_name: 'Kursi Guru', quantity: 6, status_baik: 6, status_rusak: 0 },
  { id: 'inv-6', report_id: 'report-1', item_name: 'Meja Guru', quantity: 4, status_baik: 4, status_rusak: 0 },
  { id: 'inv-7', report_id: 'report-1', item_name: 'Papan Tulis', quantity: 3, status_baik: 3, status_rusak: 0 },

  // report-2
  { id: 'inv-8', report_id: 'report-2', item_name: 'Alat Bermain Luar (Prosotan/Ayunan)', quantity: 2, status_baik: 1, status_rusak: 1 },
  { id: 'inv-9', report_id: 'report-2', item_name: 'Alat Bermain Dalam (APE)', quantity: 15, status_baik: 13, status_rusak: 2 }
];

export const systemLogs: Log[] = [
  {
    id: 'log-1',
    user_id: 'user-petugas',
    username: 'petugas',
    action: 'SUBMIT_REPORT',
    details: 'Submit laporan bulanan Juni 2026 untuk TK ABA Gergunung',
    timestamp: '2026-06-30T16:45:00Z'
  },
  {
    id: 'log-2',
    user_id: 'user-super-admin',
    username: 'admin',
    action: 'APPROVE_REPORT',
    details: 'Approve laporan bulanan Mei 2026 untuk TK ABA Gergunung',
    timestamp: '2026-06-02T08:30:00Z'
  }
];

export const initialSettings: SystemSettings = {
  google_sheets_url: 'https://docs.google.com/spreadsheets/d/1Bqgss06C6au6HfrLfF-6ywDftB7tOpN986b6QNh7ncI/edit',
  google_apps_script_url: 'https://script.google.com/macros/s/AKfycbz4C2cHkY4u6Ige3Ru595DhyhOUn9Fv-t9aI6m1seek-NJjNKXOloY9mLyoh7BT4pJV/exec',
  backup_interval: 'Bulanan',
  allow_petugas_edit_after_submit: false,
  app_title: 'SIM IGABA',
  app_subtitle: 'Klaten Utara',
  super_admin_password: 'adminn',
  admin_password: 'admin',
  petugas_password: 'petugas'
};

export const masterInventories = [
  'Alat Bermain Luar (Prosotan/Ayunan)',
  'Alat Bermain Dalam (APE)',
  'Kursi Anak',
  'Meja Anak',
  'Kursi Guru',
  'Meja Guru',
  'Papan Tulis'
];
